"""
Google: 0,1,2
AWS: 3-8
AZR: 9
CNCF FinOps: 10
CNCF: 12-13
Hashi: 14
"""
sample_data = [
    "Google Cloud This acknowledges that Jules Masterson has successfully completed all the requirements to be recognized as Series ID: 57896 Issue Date: 25 Feb 2022 Expiration Date: 25 Feb 2024 Certification ID: VAAloa Certified As: Jules Masterson Google Cloud Certified Professional Cloud Architect The non time Thomas Kurian CEO, Google Cloud GOOGLE Cloud Architect CLOUD CERTIFIED PROFESSIONAL",
    "Google Cloud This acknowledges that Nikhil Stevens has successfully completed all the requirements to be recognized as a Series ID: 52886 Issue Date: 18 Mar 2022 Expiration Date: 18 Mar 2024 Certification ID: vYTglw Certified As: Nikhil Stevens GOOGLE CLOUD CERTIFIED ASSOCIATE CLOUD ENGINEER The nationa ma Thomas Kurian CEO, Google Cloud Cloud Google Certified ASSOCIATE CLOUD ENGINEER",
    "Google Cloud This acknowledges that Matthew Brady has successfully completed all the requirements to be recognized as a Series ID: 16535 Issue Date: 8 Jun 2021 Expiration Date: 8 Jun 2023 Certification ID: Ad8hv3 Certified As: Matthew Brady GOOGLE CLOUD CERTIFIED PROFESSIONAL DATA ENGINEER The mai ma Thomas Kurian CEO, Google Cloud cloud Google Certified PROFESSIONAL DATA ENGINEER",
    "Issue Date Sep 15, 2020 aws CERTIFIED Expiration Date Sep 15, 2023 Keith Warner has successfully completed the AWS Certification requirements and has achieved their: AWS Certified Cloud Practitioner Maureen Lovergan Maureen Lonergan Director, Training and Certification Validation Number HN9Y813FDNV0QX5K Validate at: http://aws.amazon.com/verification",
    "aws certified Jacob Bronson AWS Certified Cloud Practitioner VALIDATION NUMBER: XPHV7GPLP1VQ115J VALIDATE AT: https://aws.amazon.com/verification Issue Date: Nov 26, 2020 Expiration Date: Nov 26, 2023",
    "aws CERTIFIED Issue Date May 19, 2019 Misha Ortiz AWS Certified Solutions Architect - Professional Expiration Date May 19, 2022 has successfully completed the AWS Certification requirements and has achieved their: Mamien Presse Maureen Lonergan Director, Training and Certification Validation Number YZ3HPS72ENBQQCS5 Validate at: http://aws.amazon.com/verification",
    "aws certified Francois McDonald AWS Certified Solutions Architect - Associate VALIDATION NUMBER: 37FFB4LBENQQ1PSC VALIDATE AT: https://aws.amazon.com/verification Issue Date: Feb 20, 2022 Expiration Date: Feb 20, 2025",
    "aws certified Keith Warner AWS Certified Solutions Architect - Professional VALIDATION NUMBER: 29Y3TFLJGFRQ1WKF VALIDATE AT: https://aws.amazon.com/verification Issue Date: Aug 10, 2020 Expiration Date: Aug 10, 2023",
    "aws certified Francois McDonald AWS Certified Developer - Associate VALIDATION NUMBER: NT3NNNJJPERE1Q97 VALIDATE AT: https://aws.amazon.com/verification Issue Date: Apr 08, 2022 Expiration Date: Apr 08, 2025",
    "https://learn.microsoft.com/en-us/users/danb527-2263/certifications/certification-print/certification.azure-fundamentals#edit-info-form 1/1 Microsoft Microsoft CERTIFIED FUNDAMENTALS Dan Brody (Legal name: Daniel Brody) has successfully achieved the certification Microsoft Certified: Azure Fundamentals Date of achievement: December 16, 2022 Certification Number: 1531-5121 Larya Satya Narayana Nadella N. 12/16/22, 12:17 PM Certifications - danbrody527-2263 | Microsoft Learn",
    "SC SO SC S FinOps FinOps Foundation FinOps Foundat Foundation FinOps Foundation FinOps Fino FinOps FinOps FinOps Foundation Foundat Fino Foundation FinOps Certified Practitioner The FinOps Foundation hereby certifies that Bart Legee Ops JR STORMENT, EXECUTIVE DIRECTOR FINOPS FOUNDATION Fino Founda December 23, 2022 dation Foundation has successfully completed the program requirements to be recognized as a Finops Certified Practitioner DATE OF COMPLETION hOps Foundation Foundation inOps FinOps Fin Fino Founda FinOps FinOps Fin Foundation Foundation FinOps FinOps Foundation LF-zeuk4vs3jt CERTIFICATE ID NUMBER Foundation FinOps FinOps Fino To verify the status of this certificate, please visit http://training.linuxfoundation.org/certification/verify Foundation Foundation Fin Founda F ",
    "https://learn.microsoft.com/en-us/users/franciscodelacortina-5984/certifications/certification-print/certification.azure-administrator 1/1 Microsoft Microsoft CERTIFIED ASSOCIATE Frank Myers (Legal name: Frank Myers) has successfully achieved the certification Microsoft Certified: Azure Administrator Associate Date of achievement: May 28, 2021 Valid until: May 28, 2023 Certification Number: H832-4530 Larg Satya Narayana Nadella N. 08/12/2022, 11:19 Certifications - frank-5984 | Microsoft Learn ",
    "ING FOUNDATION NATIVE CLOU CLOUD NATIVE COMPUTING FOUNDATION OUD NATIVE NATIVE COMPUTING FOUNDATION PUTING FOUNDATION LOUD NATIVE COMPUTING FOUNDATION LOUD NATIVE CLOUD COMPUTING FOUN LOUD NATIVE D NATI COMPUTING FOUNDATIO CLOUD NATIVE COMPUTING FOUNDATION COMPUTING FOUNDAT CLOUD NATIVI The Cloud Native Computing Foundation hereby certifies CERTIFIED kubernetes SECURITY SPECIALIST ATIVE S NATIV NG FOUNDATIO PRIYANKA SHARMA, GENERAL MANAGER CLOUD NATIVE COMPUTING FOUNDATION NDATIO PUTING FOUND Steve Rooker NATI OUNDATION has successfully completed the program requirements to be recognized as a ATIVE UNDATION OMPUTING May 10, 2022 DATE OF COMPLETION TING FOUNDAT Certified Kubernetes Security Specialist ATIVE O NATIV NATIVE NG FOUNDATION N CLOUD NATIVE CLOUD N CLOUD TING FOUNDATION CLOUD NATIVE CLONATIVE CLOUD FOUNDA NATIVE CLOUD NATIVE ATIV LF-iya9vve8wo CERTIFICATE ID NUMBER COMPUTING FOUNDATION UD NATIV PUTING  FOUNDATION CLOUD To verify the status of this Certificate, please visit http://training.linuxfoundation.org/certification/verify NATIVE ",
    "OUD NATIVE NATIVE CLOV NG FOUNDATION COMPUTING FOUNDATION LOUD PUTING FOUNDATION NATIVE CLOUD NATIVE CLOUD NATIVE COMPUTING FOUNDATION OUD NATIVE COMPUTING FOUNDATION COMPUTING FOUNDA OUD NATIN COMPUTING FOUNDATION CLOUD NATIVE COMPUTING FOUNDATION LOUD NATIVE The Cloud Native Computing Foundation hereby certifies that COMPUTING FOUNDAT CLOUD NATIVE G FOUND CERTIFIED kubernetes ADMINISTRATOR G FOUNDATIO NATIVE UNDATION PRIYANKA SHARMA, GENERAL MANAGER CLOUD NATIVE  COMPUTING FOUNDATION Steve Rooker OUNDATION UD NAT PUTING FOUND has successfully completed the program requirements to be recognized as a April 25, 2022 TING FOUNDA DATE OF COMPLETION OMPUTING Certified Kubernetes Administrator OUNDATION NATIVE NG FOUNDATION D NATIV N CLOUD NATIVE CLOUD FOUND TING FOUNDATION LOUD NATIVE CLOUD NATIVE CLOUD NATIVE CLOUD NATIVE LF-z7r9h79xpo CERTIFICATE ID NUMBER COMPUTING FOUNDATION UD NATIV PUTING FOUNDATIO COMPUTING FOUNDATION To verify the status of this Certificate, please visit http://training.linuxfoundation.org/certification/verify CLOUD COMPUTING NATIVE ",
    "\u2012\u2012\u2012 \u2012\u2012\u2012 HashiCorp HashiCorp Certifies that Olivier Swift Has successfully met the requirements of a Vault Associate 2022-08-31 Date Issued M Mitchell Hashimoto Arman Dudger Armon Dadgar",
    "NATIVE COMPUTING FOUNDATION LOUD NATIVE ID NATIVE CLOUD NATIVE OUD NATIVE UTING FOUNDATION COMPUTING FOUNDATI NATIVE CLOUD COMPUTING FOUNDATIO CLOUD NATIVE CLO OUD NATIV COMPUTING FOUNDATION \u043e\u043b The Cloud Native Computing Foundation hereby certifies that FOUNDATION CERTIFIED kubernetes COMPUTING FO APPLICATION DEVELOPER \u043a\u0438 NATIVE FOUNDATION Eran Chezroni has successfully completed the program requirements to be recognized as a DAN KOHN, EXECUTIVE DIRECTOR CLOUD NATIVE COMPUTING FOUNDATION Certified Kubernetes Application Developer TING FOUNDATION OUNDATION ATIVE D NATIVE, UD NATIVE PUTING FOUNDATION June 8, 2019 DATE OF COMPLETION TION OMPUTING FO OUD NO COMPUTING FOU OUD NA FOUNDATION MPUTING FOUND CLOUD N COMPUTING UD NATI NATIVE CLOUD NATIVE CKAD-1900-0833-0100 CERTIFICATE ID NUMBER CLOU COMPUT CLOUD NATIV COMPUTING FOUNDATION CLOUD NATIVE CLOC LOUD NATIVE CLOU MPUTING FOUR CLOUD COMPUTIN ",
    "aws certified Jules Guyot AWS Certified SysOps Administrator - Associate VALIDATION NUMBER: KR7VB6PJG1BEQPG5 VALIDATE AT: https://aws.amazon.com/verification Issue Date: May 27, 2020 Expiration Date: May 27, 2023 ",
    "aws certified Avi Keinan AWS Certified DevOps Engineer - Professional VALIDATION NUMBER: N9S25TYDKNR4123C VALIDATE AT: https://aws.amazon.com/verification Issue Date: Apr 22, 2021 Expiration Date: Apr 22, 2024 ",
]
